// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/suhub/Variant1.tsx": () => import("../components/mockups/suhub/Variant1.tsx"),
  "./components/mockups/suhub/Variant2.tsx": () => import("../components/mockups/suhub/Variant2.tsx"),
  "./components/mockups/suhub/Variant3.tsx": () => import("../components/mockups/suhub/Variant3.tsx")
};
